---
- hosts: all
  vars: 
    users: ['jnoriel']
  tasks:
    - name: Adds user 'jnoriel' into the wheel group
      become: true
      user:
        name: "{{ item }}"
        shell: /bin/bash
        group: wheel
      loop: "{{ users }}"
      # Change file ownership, group and mode
    - file:
        path: /home/{{ item }}
        mode: 0750
      become: true
      loop: "{{ users }}"
      # Add public SSH key to authorized_key
    - name: Set authorized key taken from file
      authorized_key:
        user: "{{ item }}"
        state: present
        key: "{{ lookup('file', './{{ item }}.pub') }}"
      loop: "{{ users }}"
      become: true
      # Line-in-file module to allow your user to perform passwordless sudo
    - lineinfile:
        path: /etc/sudoers.d/{{ item }}
        line: '{{ item }} ALL=(root) NOPASSWD:ALL'
        create: yes
        mode: 0440
        validate: '/usr/sbin/visudo -cf %s'
      become: true
      loop: "{{ users }}"


